### PR TITLE
Link Corrections

### PR DESCRIPTION
**Pull request by DanielSherlock**
Errr. Hi?

Not really sure what the procedure is for all this, but I noticed some links in your README file weren't behaving nicely, so I changed them (I had to anyway, as I wanted to try it out, and then once I did - nice job by the way - I thought I'd try and be helpful).

One thing to mention, I wasn't sure if the original _"Play PuzzlangWeb!"_ worked locally or something (which would be useful), so didn't remove it, instead adding the one which works here in Github in below it. Hope that makes sense.

Regards,
Daniel

### CODE REVIEW

**Comment by DanielSherlock** [comment]
Ah! Now I know that the link was supposed to be for people viewing it once it's been served by GithubPages, it all made sense, and I changed it so there's now just the one link (like before) that works here _and_ there - so you get the best of both worlds.

I feel somewhat (very) silly doing all this just for a link, so if it helps, I was originally trying to fix something else (something more bug-ish) as well, but later decided that came under Puzzlang, not PuzzlangWeb. I'll probably get round to that soon?

**Comment by david-pfx** [comment]
Many thanks for picking up on that. I think what happened was that I forgot the last push after I completed local testing. So I've now done that and haven't needed to use your pull, and hopefully it's OK now.
Yes, this project is just to allow serving the WebGL player. The real project is Puzzlang and any bugs you find there very much appreciated.

**Comment by DanielSherlock** [comment]
No worries! Since writing that, I've had a nose round the Puzzlang side of things and found what was causing the problem: Its not a bug in Puzzlang itself, just a few errors in the scripts of a few of the games I was using to test it out. I can fix them and submit a pull request if you wish, as they're pretty minor - and you probably have better things to be thinking about! Either way, as this PR's already sorted itself out, is it okay to close it?

**Comment by david-pfx** [comment]
If you have found some problems I'd appreciate your raising an issue so I can keep track. I wouldn't bother with a PR at this stage. I'll close this one.

**Pull request closed without merging**
